<h1>write_<?php echo  $table  ?>.php</h1>
<textarea rows="80" style="width: 100%;">
&lt;?php 
    require_once('../js/good_query.php'); 
    require_once('../js/secured.php'); 
    good_connect();
    $action  = $_POST['action']; 
    $result = 0 ;
    $allow = 1;
    if($action == 'add') { 
<?php 
		foreach($parameters->list_fields as $key => $list_field) {
 			if(View_Helper_CSCreate::isFklist($list_field) && !isset($list_field['is_status']) && View_Helper_CSCreate::IsRequired($list_field)) {
?> 
        $input_<?php echo $list_field['field'] ?> = trim($_POST['input_<?php echo  $list_field['field']; ?>']);
        if(empty($input_<?php echo $list_field['field'] ?>)) {
            $allow = 0; 
        }
<?php
			}
		}

?>
        if($allow == 1) { 
<?php 
		foreach($parameters->list_fields as $key => $list_field) {
			if(View_Helper_CSCreate::isFklist($list_field) && !isset($list_field['is_status'])) {
				if(View_Helper_CSCreate::IsRequired($list_field)) {
?>         
        $<?php echo $list_field['field'] ?> = GetSQLValueString($input_<?php echo $list_field['field'] ?> ,&quot;<?php echo $list_field['type'] ?>&quot;);
<?php 		
				} else { 
					if(isset($list_field['default_value']) && !empty($list_field['default_value'])) {
?>
		$<?php echo $list_field['field'] ?> = <?php echo $list_field['default_value']; ?>;
<?php
 						
					} else {
?>							        
        $<?php echo $list_field['field'] ?> = GetSQLValueString($_POST['input_<?php echo $list_field['field'] ?>'],&quot;<?php echo $list_field['type'] ?>&quot;);
<?php				}
				}
			}
		}

?>        
        $sql = &quot;
        INSERT INTO <?php echo $table; ?> set 
		<?php echo View_Helper_Get::helper('SqlCreate')->insertFields()->fkFields()->executeFields(); ?>
 		&quot;;
        good_query($sql);
        $result = good_last();
        }
    } elseif($action == 'update') { 
    $input_<?php echo $parameters->primary_key; ?> = GetSQLValueString($_POST['input_<?php echo $parameters->primary_key; ?>'],&quot;int&quot;);
    $update_list = array();
    
	<?php echo View_Helper_Get::helper('CodeCreate')->setShowDefaultValue(0)->DisplayFieldTypeList(); ?> 
    foreach($list as $type =&gt; $fields ) {
        foreach($fields as $field) { 
            if(isset($_POST['input_'.$field])) {
            $$field = ($type == 'text' ) ? GetSQLValueString(trim($_POST['input_'.$field]),$type):GetSQLValueString($_POST['input_'.$field] ,$type) ;
            $update_list[] = $field.&quot; = &quot;.$$field;
            } 
        }
    } 
    
    if(count($update_list) &gt;= 1) { 
    good_query(&quot;update <?php echo $table; ?> set &quot;.implode(&quot;,&quot;,$update_list).&quot; WHERE <?php echo $parameters->primary_key; ?> = $input_<?php echo $parameters->primary_key; ?>;&quot;);
    $result = good_query_assoc(&quot;select * from  <?php echo $table; ?> WHERE <?php echo $parameters->primary_key; ?> = $input_<?php echo $parameters->primary_key; ?>;&quot;);
    } 
<?php if($parameters->is_status_exist == 1)  { ?>    
    } elseif($action == 'delete') { 
    $<?php echo $parameters->primary_key; ?> = GetSQLValueString($_POST['<?php echo $parameters->primary_key; ?>'],&quot;int&quot;);
        if(!empty($<?php echo $parameters->primary_key; ?>)) {
            good_query(&quot;update <?php echo $table; ?> set <?php echo $parameters->list_fields[$parameters->status_key]['field'] ?> = -1 WHERE <?php echo $parameters->primary_key; ?> = $<?php echo $parameters->primary_key; ?>;&quot;);
            $result = 1;
        }
    }
<?php } else { ?>   
    } elseif($action == 'delete') { 
        $input_<?php echo $parameters->primary_key; ?> = $_POST['input_<?php echo $parameters->primary_key; ?>']; 
        if(empty($input_<?php echo $parameters->primary_key; ?>)) {
        echo json_encode($result);
        return false; 
        }
        $<?php echo $parameters->primary_key; ?> = GetSQLValueString($input_<?php echo $parameters->primary_key; ?>,&quot;int&quot;); 
        good_query(&quot;delete from  <?php echo $table; ?> WHERE <?php echo $parameters->primary_key; ?> = $<?php echo $parameters->primary_key; ?>;&quot;);
        $result = 1;
    } 
<?php } ?>    
    echo json_encode($result);
    good_close();
?&gt;

</textarea>
