<h1>dashboard_<?php echo  $table  ?>.php</h1>
<textarea   rows="300" style="width:100%">
&lt;?php 
  require_once('includes/header.php'); ?&gt;
    &lt;div class=&quot;row&quot;&gt;
    &lt;div class=&quot;row_label3&quot;&gt;
    &lt;span&gt;<?php echo $parameters->table_title; ?>&lt;/span&gt;
    &lt;/div&gt;
    &lt;/div&gt;
    &lt;div class=&quot;row&quot;&gt;
    &lt;div class=&quot;row_label&quot;&gt;
    &lt;h2&gt;Details&lt;/h2&gt;
    &lt;/div&gt;
    &lt;div class=&quot;row_content row_content_main_margin&quot;  id=&quot;div_tms_account&quot; &gt;
    <?php 
            foreach($parameters->list_fields as $key => $list_field) {
                if(View_Helper_CSCreate::isFklist($list_field) && View_Helper_CSCreate::isStatus($key) && View_Helper_CSCreate::isDefaultValue($list_field)) {
    ?>   
    &lt;label class=&quot;label_lg&quot;&gt;
    &lt;span&gt;<?php echo $list_field['field_name'] ?>&lt;/span&gt;
    &lt;input type=&quot;text&quot; id=&quot;input_<?php echo $list_field['field'] ?>&quot; class=&quot;input_lg input_<?php echo $list_field['field'] ?>&quot; value=&quot;&quot; &gt;
    &lt;/label&gt;  
    <?php
                } 
            }
    ?>
    &lt;label class=&quot;label_lg&quot;&gt;
    &lt;span&gt;&amp;nbsp;&lt;/span&gt;
    &lt;input type=&quot;button&quot; value=&quot;add&quot; id=&quot;btn_add&quot; class=&quot;btn_med_fill&quot; <?php echo $parameters->primary_key; ?>=&quot;0&quot;&gt;
    &lt;/label&gt; 
    &lt;label class=&quot;label_med&quot;&gt;
    &lt;span&gt;&amp;nbsp;&lt;/span&gt;
    &lt;input type=&quot;button&quot; value=&quot;cancel&quot; id=&quot;btn_cancel&quot; class=&quot;btn_med_fill&quot; style=&quot;display:none&quot;&gt;
    &lt;/label&gt; 
    &lt;/div&gt;
    &lt;/div&gt;

  &lt;div class=&quot;row&quot;&gt;
  &lt;div class=&quot;row_label&quot;&gt;
  &lt;h2&gt;FILTER&lt;/h2&gt;
  &lt;p&gt;Selected/Total&lt;/p&gt;
  &lt;p&gt;Total: &lt;span id=&quot;total_result&quot;&gt;0&lt;/span&gt;&lt;/p&gt;
  &lt;/div&gt;
  &lt;div class=&quot;row_content row_content_main_margin&quot;&gt;
  
<?php 
        foreach($parameters->list_fields as $key => $list_field) {
            if(View_Helper_CSCreate::isFklist($list_field) && View_Helper_CSCreate::isStatus($key) && View_Helper_CSCreate::isDefaultValue($list_field)) {
?>   
  &lt;label class=&quot;label_lg&quot;&gt;
  &lt;span&gt;<?php echo $list_field['field_name'] ?>&lt;/span&gt;
  &lt;input type=&quot;text&quot; id=&quot;search_<?php echo $list_field['field'] ?>&quot; class=&quot;input_lg input_<?php echo $list_field['field'] ?>&quot; value=&quot;&quot; &gt;
  &lt;/label&gt;  
<?php
            } 
        }
?> 

  &lt;label class=&quot;label_lg&quot;&gt;
  &lt;span&gt;&amp;nbsp;&lt;/span&gt;
  &lt;input type=&quot;button&quot; value=&quot;Refresh&quot; id=&quot;btn_refresh&quot; class=&quot;btn_med_fill&quot;&gt;
  &lt;/label&gt; 
  
  &lt;/div&gt;
  &lt;/div&gt;

  &lt;table id=&quot;<?php echo $table; ?>_table&quot; class=&quot;main_dynamic_table dynamic_table <?php echo $table; ?>_table&quot; width=&quot;100%&quot;&gt; 
  &lt;thead&gt; 
  &lt;tr&gt;
  &lt;th class=&quot;label_sm&quot;&gt;&lt;span&gt;Type&lt;/span&gt;&lt;/th&gt;
<?php 
        foreach($parameters->list_fields as $key => $list_field) {
            if(View_Helper_CSCreate::isFklist($list_field) && View_Helper_CSCreate::isStatus($key) && View_Helper_CSCreate::isDefaultValue($list_field)) {
?>   
  &lt;th class=&quot;label_sm&quot;&gt;&lt;span&gt;<?php echo $list_field['field_name'] ?>&lt;/span&gt;&lt;/th&gt;
<?php
            } 
        }
?> 
  &lt;th class=&quot;label_lg&quot;  data-sorter=&quot;false&quot;&gt;&lt;span&gt;Tools&lt;/span&gt;&lt;/th&gt;
  &lt;/tr&gt;
  &lt;/thead&gt;
  &lt;tbody aria-live=&quot;polite&quot; aria-relevant=&quot;all&quot; class=&quot;tbody_<?php echo $table; ?>_table&quot;&gt;
  &lt;/tbody&gt; 
  &lt;/table&gt;
         
  &lt;script type=&quot;application/javascript&quot; language=&quot;javascript&quot;&gt; 
   
function edit<?php echo str_replace(' ', '',$parameters->table_title); ?>() {
var <?php echo $parameters->primary_key; ?> = $(&quot;#btn_add&quot;).attr('<?php echo $parameters->primary_key; ?>');
var dataString = '';
<?php 
		foreach($parameters->list_fields as $key => $list_field) {
 			if(View_Helper_CSCreate::isFklist($list_field) && !View_Helper_CSCreate::IsRequired($list_field)) {
?>       
  var input_<?php echo $list_field['field'] ?>  =  $.trim($('#input_<?php echo $list_field['field'] ?>').val()); 
  if(input_<?php echo $list_field['field'] ?> == '' ) {
  $('#input_<?php echo $list_field['field'] ?>').focus();
  showMessage('<?php echo $list_field['field_name'] ?> must not be empty', 'error'); 
  return false;
  }
<?php
			}  
		}

?> 

dataString += '&amp;input_<?php echo $parameters->primary_key; ?>=' + <?php echo $parameters->primary_key; ?>;
<?php foreach($store_fields as $store_field) { ?>
dataString += '&amp;input_<?php echo $store_field; ?>='+<?php echo $store_field; ?>; 
<?php } ?>   

writeDataConfirm(dataString, 'write_<?php echo $parameters->primary_key; ?>.php', function(row) {
if (row == 0) {
showMessage('Error.', 'error');
return false;
}
showMessage('<?php echo $parameters->table_title ?> Added.', 'success');
if(<?php echo $parameters->primary_key; ?> &lt;= 0) {
add<?php echo str_replace(' ', '',$parameters->table_title); ?>Row(row);
reset_boxes();
} else {
   <?php foreach($store_fields as $store_field) { ?>
	<?php if(in_array($store_field,$parameters->enum_list)) { ?>	
$('#tr_<?php echo $table; ?>_'+row['<?php echo $parameters->primary_key; ?>']+' .<?php echo $store_field; ?>').html(enum_field_list['<?php echo $store_field; ?>'][row['<?php echo $store_field; ?>']]);
	<?php } else { ?>
$('#tr_<?php echo $table; ?>_'+row['<?php echo $parameters->primary_key; ?>']+' .<?php echo $store_field; ?>').html(row['<?php echo $store_field; ?>']);
 	<?php } ?>
  <?php } ?>  
}
});
}
  function get<?php echo str_replace(' ', '',$parameters->table_title); ?>() {
  var dataString = '&amp;<?php echo $parameters->primary_key; ?>=0'; 

   <?php foreach($store_fields as $store_field) { ?>
          if($(&quot;#search_<?php echo $store_field; ?>&quot;).val() != '') {
                dataString += '&amp;<?php echo $store_field; ?>='+$(&quot;#search_<?php echo $store_field; ?>&quot;).val();
          }

  <?php } ?>    
  $('#<?php echo $table; ?>_table tbody').html('');
  startSpin();
  getData(dataString, 'get_<?php echo $table; ?>.php', function(rows){
  stopSpin();
  if(rows == 0) {
  $(&quot;#<?php echo $table; ?>_table&quot;).trigger(&quot;update&quot;);
  return false;
  }
  for(var i in rows) {
  add<?php echo str_replace(' ', '',$parameters->table_title); ?>Row(rows[i]);
  }
  $(&quot;#<?php echo $table; ?>_table&quot;).trigger(&quot;update&quot;);
  });
  
  }
  
  function add<?php echo str_replace(' ', '',$parameters->table_title); ?>Row(row) {
  var echo = '&lt;tr id=&quot;tr_<?php echo $table; ?>_'+row['<?php echo $parameters->primary_key; ?>']+'&quot;&gt;';

  <?php foreach($store_fields as $store_field) { ?>
	  <?php if(in_array($store_field,$parameters->enum_list)) { ?>
      echo += '&lt;td class=&quot;<?php echo $store_field; ?>&quot;&gt;'+enum_field_list['<?php echo $store_field; ?>'][row['<?php echo $store_field; ?>']]+'&lt;/td&gt;';
      <?php } else { ?>
      echo += '&lt;td class=&quot;<?php echo $store_field; ?>&quot;&gt;'+row['<?php echo $store_field; ?>']+'&lt;/td&gt;';
      <?php } ?>
  <?php } ?>   
  echo += '&lt;td&gt;&lt;a class=&quot;btn_edit&quot; <?php echo $parameters->primary_key; ?>=&quot;'+row['<?php echo $parameters->primary_key; ?>']+'&quot;&gt;edit&lt;/a&gt; ';
  echo += '| &lt;a class=&quot;btn_delete&quot; <?php echo $parameters->primary_key; ?>=&quot;'+row['<?php echo $parameters->primary_key; ?>']+'&quot;&gt;delete&lt;/a&gt;&lt;/td&gt;';
  echo += '&lt;/td&gt;';
  echo += '&lt;/tr&gt;';
  $('.<?php echo $table; ?>_table tbody').append(echo);
  }
  
  function reset_boxes() {
  <?php foreach($store_fields as $store_field) { ?>
  $(&quot;#input_<?php echo $store_field; ?>&quot;).val('');    
  <?php } ?>   
  $(&quot;#btn_add&quot;).removeAttr('<?php echo $parameters->primary_key; ?>');
  $(&quot;#btn_add&quot;).val('Add');
  $(&quot;#btn_cancel&quot;).attr('type','hidden'); 
  }
 function init() {
  $( &quot;#btn_add&quot; ).click(function() {
  var optionvalue = $( this).val();
  switch(optionvalue) {
  case 'Add':
  add<?php echo str_replace(' ', '',$parameters->table_title); ?>();
  break;
  case 'Update':
  edit<?php echo str_replace(' ', '',$parameters->table_title); ?>(); 
  break;
  } 
  }); 
  
  $( &quot;#btn_cancel&quot; ).click(function() {
  reset_boxes();
  }); 
  $( &quot;#btn_refresh&quot; ).click(function() {
  get<?php echo str_replace(' ', '',$parameters->table_title); ?>();
  }); 
  
  $('body').on('click', '.btn_edit', function(){
  var <?php echo $parameters->primary_key; ?> = $(this).attr('<?php echo $parameters->primary_key; ?>');
  
  var dataString = '';
  dataString += '&amp;<?php echo $parameters->primary_key; ?>='+<?php echo $parameters->primary_key; ?>; 
  getData(dataString, 'get_<?php echo $table; ?>.php', function (row){
  if(row == 0) {
  showMessage('Error.', 'error');
  return false;
  }
  var list = new Array('<?php echo $parameters->primary_key; ?>',<?php echo View_Helper_Get::helper('CodeCreate')->DisplayJavascriptFieldList() ?>); 
 
  <?php foreach($store_fields as $store_field) { ?>
      $(&quot;#input_<?php echo $store_field; ?>&quot;).val(row['<?php echo $store_field; ?>']);
  <?php } ?>   
  $(&quot;#btn_add&quot;).val('Update');
  $(&quot;#btn_add&quot;).attr('<?php echo $parameters->primary_key; ?>',row['<?php echo $parameters->primary_key; ?>']);
  $(&quot;#btn_cancel&quot;).attr('type','button');
  });
  
  });
  
  $('body').on('click', '.btn_delete', function(){
  var <?php echo $parameters->primary_key; ?> = $(this).attr('<?php echo $parameters->primary_key; ?>');
  
  var dataString = '';
  confirm_popup('Delete','Are you sure you want to delete this file?',function(){
  dataString += '&amp;<?php echo $parameters->primary_key; ?>='+<?php echo $parameters->primary_key; ?>; 
  writeDataConfirm(dataString, 'delete_<?php echo $table; ?>.php', function(row){
  if(row == 1) {
  $('#tr_<?php echo $table; ?>_'+<?php echo $parameters->primary_key; ?>).remove();
  }
  });
  reset_boxes(); 
  });
  
  }); 
 
  get<?php echo str_replace(' ', '',$parameters->table_title); ?>(); 
  $(&quot;#<?php echo $table; ?>_table&quot;).tablesorter( {} ); 
  
  }
  
  init();
  &lt;/script&gt;
  &lt;?php require_once('js/footer.php'); ?&gt;
 
</textarea>


