<h1>get_<?php echo  $table  ?>.php</h1>
<textarea  rows="50"  style="width: 100%;">
&lt;?php 
require_once('../js/good_query.php'); 
require_once('../js/secured.php');

good_connect();
 
$UserID = 1;
$GroupID = 1;
$CompanyID  =23;
<?php 
		$fields = array();	
		foreach($parameters->list_fields as $key => $list_field) {
			if(View_Helper_CSCreate::isFklist($list_field) ) {
?>
        $<?php echo str_replace('tms_','',$list_field['field']); ?>_filter = ""; 	
<?php		
			}
		}

?>
$<?php echo $parameters->primary_key; ?> = intval(GetSQLValueString($_POST['<?php echo $parameters->primary_key; ?>'],"int"));
if($<?php echo $parameters->primary_key; ?> <= 0) { 
  
<?php 
		$fields = array();	
		foreach($parameters->list_fields as $key => $list_field) {
		$tmp_field = str_replace('tms_','',$list_field['field']);	
			if(View_Helper_CSCreate::isFklist($list_field) ) {
?>
	if(isset($_POST['<?php echo $tmp_field ?>'])) {	 
        $<?php echo $tmp_field ?> = GetSQLValueString($_POST['<?php echo $tmp_field ?>'],"<?php echo $list_field['type'] ?>");
        $<?php echo $tmp_field ?>_filter = " AND <?php echo $list_field['field'] ?> = ".$<?php echo $tmp_field ?>; 						
	} 
<?php			 
		$fields[] = $list_field['field']."_filter";
 			}
		}

?>
  
$<?php echo $table; ?>_table = good_query_table("SELECT * FROM <?php echo $table; ?> WHERE 1=1 AND <?php echo View_Helper_Get::helper('SqlCreate')->fkWhere()->statusWhere()->executeWhere(); ?> $<?php echo implode(' $',$fields); ?>");
} else {
    
    if(empty($<?php echo $parameters->primary_key; ?>)) {
        echo json_encode(array());	
        return false;	
    }
    
$<?php echo $table; ?>_table = good_query_assoc("SELECT * FROM <?php echo $table; ?> where <?php echo View_Helper_Get::helper('SqlCreate')->fkWhere()->statusWhere()->executeWhere(); ?>  AND <?php echo $parameters->primary_key; ?> = $<?php echo $parameters->primary_key; ?> ");

}
echo json_encode($<?php echo $table; ?>_table);

good_close();

?&gt; 
</textarea>
