<h1>write_<?php echo  $table  ?>.php</h1>
<textarea rows="80" style="width: 100%;">
&lt;?php 
    require_once('../js/good_query.php'); 
    require_once('../js/secured.php'); 
    good_connect();
    $result = 0 ;
    $allow = 1;
    $UserID = 1;
    $GroupID = 1;
    $CompanyID  =1;   
<?php 
		$update_fields = array();	
		foreach($parameters->list_fields as $key => $list_field) {
			if(View_Helper_CSCreate::isFklist($list_field) && !isset($list_field['is_status'])) {
 ?>         
        $<?php echo $list_field['field'] ?> = GetSQLValueString($_POST['input_<?php echo $list_field['field'] ?>'],&quot;<?php echo $list_field['type'] ?>&quot;);
<?php
		$update_fields[] = $list_field['field'].'=$'.$list_field['field'];
			}
		}

?>
    $input_<?php echo $parameters->primary_key; ?> = intval(GetSQLValueString($_POST['input_<?php echo $parameters->primary_key; ?>'],&quot;int&quot;));    
    if($input_<?php echo $parameters->primary_key; ?> <= 0) { 
 
        good_query(&quot;
        INSERT INTO <?php echo $table; ?> SET 
		<?php echo View_Helper_Get::helper('SqlCreate')->insertFields()->fkFields()->executeFields(); ?>
 		;&quot;);
        $result = good_last();
       
    } else { 

         
  
        
         good_query(&quot;UPDATE <?php echo $table; ?> 
        SET  
        <?php echo implode(",\n",$update_fields)."\n"; ?>
         WHERE <?php echo $parameters->primary_key; ?> = $input_<?php echo $parameters->primary_key; ?>;&quot;);
         
        $result = good_query_assoc(&quot;select * from  <?php echo $table; ?> WHERE <?php echo $parameters->primary_key; ?> = $input_<?php echo $parameters->primary_key; ?>;&quot;);
  	}
    echo json_encode($result);
    good_close();
?&gt;

</textarea>
